vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boost-ext/ut
    REF "v${VERSION}"
    SHA512 f95bdc9ba483f309bdcbe57d2fef92a0b4301bdb1c83700e711ac152c72a76b1d502a16462cca48074db024c0eb97920ffca7b3236f04c3bb40080c672c80f50
    HEAD_REF master
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBOOST_UT_ALLOW_CPM_USE=OFF
        -DBOOST_UT_BUILD_BENCHMARKS=OFF
        -DBOOST_UT_BUILD_EXAMPLES=OFF
        -DBOOST_UT_BUILD_TESTS=OFF
        -DBOOST_UT_DISABLE_MODULE=ON
    MAYBE_UNUSED_VARIABLES
        BOOST_UT_ALLOW_CPM_USE
        INCLUDE_INSTALL_DIR
)
vcpkg_cmake_install()
vcpkg_copy_pdbs()

# Criar os arquivos de configuração manualmente no local correto
file(WRITE "${CURRENT_PACKAGES_DIR}/share/ut/ut-config.cmake" [=[
# This file was automatically generated by vcpkg
get_filename_component(UT_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(UT_INCLUDE_DIR "${UT_CMAKE_DIR}/../../include" ABSOLUTE)
set(UT_INCLUDE_DIRS "${UT_INCLUDE_DIR}")
set(UT_FOUND TRUE)

# Define o alvo ut::ut para compatibilidade
add_library(ut::ut INTERFACE IMPORTED)
set_target_properties(ut::ut PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${UT_INCLUDE_DIRS}"
)

# Define o alvo Boost::ut para compatibilidade com código que usa esse nome
add_library(Boost::ut INTERFACE IMPORTED)
set_target_properties(Boost::ut PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${UT_INCLUDE_DIRS}"
)
]=])

file(WRITE "${CURRENT_PACKAGES_DIR}/share/ut/ut-config-version.cmake" [=[
# This file was automatically generated by vcpkg
set(PACKAGE_VERSION "2.3.1")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
]=])

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug"
                    "${CURRENT_PACKAGES_DIR}/lib"
)

configure_file("${CMAKE_CURRENT_LIST_DIR}/usage"
               "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")